#!/usr/bin/with-contenv bash

# make folders
mkdir -p /app/sabnzbd /downloads /incomplete-downloads

if [ ! -f "/app/sabnzbd/SABnzbd.py" ]; then
LATEST_RELEASE=$(curl -sX GET "https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest" | \
awk '/tag_name/{print $4;exit}' FS='[""]')

curl -o \
	/tmp/sabnzbd.tar.gz -L \
https://github.com/sabnzbd/sabnzbd/releases/download/"${LATEST_RELEASE}"/SABnzbd-"${LATEST_RELEASE}"-src.tar.gz

tar xvf /tmp/sabnzbd.tar.gz -C /app/sabnzbd --strip-components=1
rm -f /tmp/sabnzbd.tar.gz
fi

# permissions
chown -R abc:abc /app/sabnzbd
chown abc:abc /downloads /incomplete-downloads
